# BASELINE (NO TTT) - Aggressive Test Comparison
# data
data:
  train_data: /sise/eliyanac-group/ron_al/seamless_interaction/daily_format_output/dailytalk.jsonl
  eval_data: /sise/eliyanac-group/ron_al/seamless_interaction/daily_format_output/dailytalk.jsonl
  shuffle: false

ttt:
  enable: false  # TTT DISABLED for baseline comparison
  layers: "29,30,31"  # Same layers but disabled
  base_lr: 0.01   # Same settings for fair comparison
  mini_batch_size: 16
  persistent_states: true

# model
moshi_paths: 
  hf_repo_id: "kyutai/moshiko-pytorch-bf16"

full_finetuning: false 
lora:
  enable: true 
  rank: 64
  scaling: 2.
  ft_embed: false 

paper_metrics:
  paper_metrics_eval: true
  paper_metrics_freq: 10  # Evaluate every 10 steps
  paper_metrics_use_silence: true
  paper_metrics_use_user_stream: false
  sblimp_audio_dir: /sise/eliyanac-group/ron_al/sblimp_data/sLM21_dataset/syntactic/test/
  sblimp_gold_csv: /sise/eliyanac-group/ron_al/sblimp_data/sLM21_dataset/syntactic/test/gold.csv
  sblimp_max_pairs: 10
  sstory_audio_dir: /sise/eliyanac-group/ron_al/sSC/sSC/
  sstory_max_pairs: 10
  swuggy_audio_dir: /sise/eliyanac-group/ron_al/sblimp_data/sLM21_dataset/lexical/test/
  swuggy_gold_csv: /sise/eliyanac-group/ron_al/sblimp_data/sLM21_dataset/lexical/test/gold.csv
  swuggy_max_pairs: 10
  tstory_audio_dir: /sise/eliyanac-group/ron_al/tSC/tSC/
  tstory_max_pairs: 10
  # LibriLight Long Context Evaluation (TTT Paper methodology)
  librilight_audio_dir: /sise/eliyanac-group/ron_al/librilight/extracted_medium/medium/
  librilight_evaluation_mode: single_book
  librilight_speaker_id: "100"
  librilight_book_name: "emerald_city_librivox_64kb_mp3"
  librilight_max_chapters: 3
  librilight_num_sequences: 1

first_codebook_weight_multiplier: 100.
text_padding_weight: .5

# optim - identical to TTT aggressive for fair comparison
duration_sec: 300  # Same duration as TTT aggressive
batch_size: 1      # Same batch size
max_steps: 2000    # Same number of steps
gradient_checkpointing: true
optim:
  lr: 1e-6         # Same learning rate
  weight_decay: 0.1
  pct_start: 0.05

# other
seed: 42  # Same seed for fair comparison
log_freq: 10
eval_freq: 50  # Same eval frequency
do_eval: true
do_ckpt: true
ckpt_freq: 50

save_adapters: true

run_dir: /sise/eliyanac-group/ron_al/baseline_aggressive_comparison

wandb:
  project: ttt-moshi-long-conversations
  offline: false
  run_name: baseline_aggressive_comparison