# data
data:
  train_data: /sise/eliyanac-group/ron_al/seamless_interaction/daily_format_output/dailytalk.jsonl
  eval_data: /sise/eliyanac-group/ron_al/seamless_interaction/daily_format_output/dailytalk.jsonl
  shuffle: false

ttt:
  enable: true  
  layers: "15,16,31"  # Same layers but with smaller gating
  base_lr: 0.1
  mini_batch_size: 16
  persistent_states: true
  # NEW: Much smaller initial gating alpha to prevent forgetting
  initial_gating_alpha: 0.01  # Start at 1% instead of 10%

# model
moshi_paths: 
  hf_repo_id: "kyutai/moshiko-pytorch-bf16"

full_finetuning: false
lora:
  enable: true
  rank: 64
  scaling: 2.
  ft_embed: false

paper_metrics:
  paper_metrics_eval: true
  paper_metrics_freq: 50
  # OPTIMAL CONFIGURATION: Natural silence codes for +2-6% performance boost
  paper_metrics_use_silence: true
  # Cross-stream evaluation (experimental - for architecture research)
  paper_metrics_use_user_stream: false
  sblimp_audio_dir: /sise/eliyanac-group/ron_al/sblimp_data/sLM21_dataset/syntactic/test/
  sblimp_gold_csv: /sise/eliyanac-group/ron_al/sblimp_data/sLM21_dataset/syntactic/test/gold.csv
  sblimp_max_pairs: 10
  sstory_audio_dir: /sise/eliyanac-group/ron_al/sSC/sSC/
  sstory_max_pairs: 10
  swuggy_audio_dir: /sise/eliyanac-group/ron_al/sblimp_data/sLM21_dataset/lexical/test/
  swuggy_gold_csv: /sise/eliyanac-group/ron_al/sblimp_data/sLM21_dataset/lexical/test/gold.csv
  swuggy_max_pairs: 10
  tstory_audio_dir: /sise/eliyanac-group/ron_al/tSC/tSC/
  tstory_max_pairs: 10
  # LibriLight Long Context Evaluation (TTT Paper methodology)
  librilight_audio_dir: /sise/eliyanac-group/ron_al/librilight/extracted_medium/medium/
  librilight_evaluation_mode: single_book
  librilight_speaker_id: "100"
  librilight_book_name: "emerald_city_librivox_64kb_mp3"
  librilight_max_chapters: 3
  librilight_num_sequences: 1

first_codebook_weight_multiplier: 100.
text_padding_weight: .5

# optim
duration_sec: 15
batch_size: 1
max_steps: 1000
gradient_checkpointing: true
optim:
  lr: 1e-6
  weight_decay: 0.1
  pct_start: 0.05

# other
seed: 42
log_freq: 10
eval_freq: 50
do_eval: true
do_ckpt: true
ckpt_freq: 200

save_adapters: true

run_dir: /sise/eliyanac-group/ron_al/seamless_ttt_fixed
 
wandb:
  project: ttt-moshi-production
  offline: false
  run_name: seamless_ttt_fixed